package svgconv

import (
	"strings"
	"testing"
)

// rootTag extracts the root <svg ...> start tag so assertions target the part
// of the document the normalizer rewrites, not incidental body content.
func rootTag(t *testing.T, svg string) string {
	t.Helper()
	i := strings.Index(svg, "<svg")
	if i < 0 {
		t.Fatalf("no <svg tag in %q", svg)
	}
	j := strings.Index(svg[i:], ">")
	if j < 0 {
		t.Fatalf("unterminated <svg tag in %q", svg)
	}
	return svg[i : i+j+1]
}

// krokiRootSVG mirrors the root tag PlantUML diagrams come back with from
// Kroki: fixed pixel sizing duplicated in the style attribute, a hardcoded
// white background, and preserveAspectRatio="none".
const krokiRootSVG = `<svg xmlns="http://www.w3.org/2000/svg" data-diagram-type="SEQUENCE" height="210" preserveAspectRatio="none" style="width:198px;height:210px;background:#FFFFFF;" viewBox="0 0 198 210" width="198" zoomAndPan="magnify"><g><rect fill="#E2E2F0" height="30" width="50" x="10" y="10"/><text fill="#181818" x="12" y="25">Alice</text></g></svg>`

func TestNormalizeForInline_KrokiRoot(t *testing.T) {
	got := NormalizeForInline(krokiRootSVG)
	root := rootTag(t, got)

	if strings.Contains(root, "background") {
		t.Errorf("root tag still has a background: %q", root)
	}
	if strings.Contains(root, "preserveAspectRatio") {
		t.Errorf("root tag still has preserveAspectRatio: %q", root)
	}
	if !strings.Contains(root, `width="100%"`) {
		t.Errorf("root tag missing width=\"100%%\": %q", root)
	}
	if !strings.Contains(root, `viewBox="0 0 198 210"`) {
		t.Errorf("root tag lost its viewBox: %q", root)
	}
	// The pixel height stays as an intrinsic size for renderers that ignore
	// CSS; height:auto lets CSS-aware renderers derive it from the viewBox.
	if !strings.Contains(root, `height="210"`) {
		t.Errorf("root tag lost its intrinsic height: %q", root)
	}
	if !strings.Contains(root, "height:auto") {
		t.Errorf("root tag missing style height:auto: %q", root)
	}
	// Shape-level colors must survive untouched.
	if !strings.Contains(got, `fill="#E2E2F0"`) || !strings.Contains(got, `fill="#181818"`) {
		t.Errorf("normalized SVG lost shape-level colors: %q", got)
	}
}

// Mermaid carries its fixed size as max-width in the style attribute, which
// must be stripped or it caps the diagram at its original pixel width.
func TestNormalizeForInline_MermaidMaxWidthStripped(t *testing.T) {
	in := `<svg xmlns="http://www.w3.org/2000/svg" id="m1" viewBox="0 0 320.5 172" style="max-width: 320.5px; background-color: white;" width="100%"><g/></svg>`
	root := rootTag(t, NormalizeForInline(in))

	if strings.Contains(root, "max-width") {
		t.Errorf("max-width survived: %q", root)
	}
	if strings.Contains(root, "background") {
		t.Errorf("background-color survived: %q", root)
	}
	if !strings.Contains(root, `width="100%"`) || !strings.Contains(root, `viewBox="0 0 320.5 172"`) {
		t.Errorf("scalable sizing lost: %q", root)
	}
}

func TestNormalizeForInline_SynthesizesViewBox(t *testing.T) {
	got := NormalizeForInline(`<svg xmlns="http://www.w3.org/2000/svg" width="100" height="50"><rect width="100" height="50"/></svg>`)
	root := rootTag(t, got)

	if !strings.Contains(root, `viewBox="0 0 100 50"`) {
		t.Errorf("expected synthesized viewBox, got: %q", root)
	}
	if !strings.Contains(root, `width="100%"`) {
		t.Errorf("expected width=\"100%%\", got: %q", root)
	}
	// The inner rect's sizing is content, not root sizing.
	if !strings.Contains(got, `<rect width="100" height="50"/>`) {
		t.Errorf("inner elements were modified: %q", got)
	}
}

// A quoted attribute value containing '>' is well-formed XML and must not
// truncate the root tag or leak fragments into the document body.
func TestNormalizeForInline_GtInAttributeValue(t *testing.T) {
	in := `<svg xmlns="http://www.w3.org/2000/svg" data-note="a > b" width="10" height="10"><g/></svg>`
	got := NormalizeForInline(in)

	if !strings.Contains(got, `viewBox="0 0 10 10"`) || !strings.Contains(got, `width="100%"`) {
		t.Errorf("sizing not normalized: %q", got)
	}
	if !strings.HasSuffix(got, "<g/></svg>") {
		t.Errorf("document body corrupted: %q", got)
	}
}

// An <svg literal inside a leading comment (Graphviz emits generator
// comments) must not be mistaken for the root element.
func TestNormalizeForInline_SkipsPrologAndComments(t *testing.T) {
	in := `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by graphviz --><!-- <svg fake="1"> -->
<svg xmlns="http://www.w3.org/2000/svg" width="10" height="20"><g/></svg>`
	got := NormalizeForInline(in)

	if !strings.Contains(got, `viewBox="0 0 10 20"`) {
		t.Errorf("real root not normalized: %q", got)
	}
	if !strings.Contains(got, `<!-- <svg fake="1"> -->`) {
		t.Errorf("comment was modified: %q", got)
	}
}

// A style declaration whose value legally contains ';' (a data: URI) must not
// be corrupted by declaration splitting.
func TestNormalizeForInline_DataURIStyleSurvives(t *testing.T) {
	in := `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10" width="10" style="background-image:url(data:image/png;base64,AAA);font-family:Arial"><g/></svg>`
	root := rootTag(t, NormalizeForInline(in))

	if strings.Contains(root, "background-image") || strings.Contains(root, "data:image/png") {
		t.Errorf("background-image not fully removed: %q", root)
	}
	if !strings.Contains(root, "font-family:Arial") {
		t.Errorf("unrelated declaration lost: %q", root)
	}
}

// NaN/Inf/negative dimensions must not synthesize an invalid viewBox (which
// would make the diagram unrenderable); sizing stays untouched.
func TestNormalizeForInline_InvalidDimensionsKept(t *testing.T) {
	for _, in := range []string{
		`<svg xmlns="http://www.w3.org/2000/svg" width="NaN" height="Inf"><g/></svg>`,
		`<svg xmlns="http://www.w3.org/2000/svg" width="-10" height="-20"><g/></svg>`,
		`<svg xmlns="http://www.w3.org/2000/svg" width="0" height="20"><g/></svg>`,
	} {
		got := NormalizeForInline(in)
		if strings.Contains(got, "viewBox") || strings.Contains(got, "100%") {
			t.Errorf("invalid dimensions produced a scalable rewrite: %q -> %q", in, got)
		}
	}
}

// An empty or malformed viewBox is not scalable on its own; with usable
// width/height it is replaced, without them the sizing stays untouched.
func TestNormalizeForInline_InvalidViewBox(t *testing.T) {
	got := NormalizeForInline(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="" width="10" height="20"><g/></svg>`)
	root := rootTag(t, got)
	if !strings.Contains(root, `viewBox="0 0 10 20"`) || !strings.Contains(root, `width="100%"`) {
		t.Errorf("invalid viewBox not replaced from dimensions: %q", root)
	}
	if !strings.Contains(root, `height="20"`) {
		t.Errorf("intrinsic height lost: %q", root)
	}

	in := `<svg xmlns="http://www.w3.org/2000/svg" viewBox="" width="10em" height="5em"><g/></svg>`
	got = NormalizeForInline(in)
	if strings.Contains(got, "100%") || !strings.Contains(got, `height="5em"`) {
		t.Errorf("unscalable input with invalid viewBox was rewritten: %q", got)
	}
}

func TestNormalizeForInline_UnscalableSizingKept(t *testing.T) {
	in := `<svg xmlns="http://www.w3.org/2000/svg" width="10em" height="5em"></svg>`
	got := NormalizeForInline(in)

	// No viewBox and no px dimensions to derive one from: sizing must be
	// left alone rather than made 100% with no aspect ratio to anchor it.
	if !strings.Contains(got, `width="10em"`) || !strings.Contains(got, `height="5em"`) {
		t.Errorf("unscalable sizing was rewritten: %q", got)
	}
}

func TestNormalizeForInline_NotSVGUnchanged(t *testing.T) {
	for _, in := range []string{
		`{"error": "not an svg"}`,
		`<html><body>nope</body></html>`,
		``,
	} {
		if got := NormalizeForInline(in); got != in {
			t.Errorf("non-SVG input was modified: %q -> %q", in, got)
		}
	}
}

func TestCleanRootStyle(t *testing.T) {
	for _, tc := range []struct{ in, want string }{
		{"width:198px;height:210px;background:#FFFFFF;", ""},
		{"max-width: 320.5px; background-color: white;", ""},
		{"background:#FFF;color:red", "color:red"},
		{"", ""},
	} {
		if got := cleanRootStyle(tc.in); got != tc.want {
			t.Errorf("cleanRootStyle(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}
